# Public Yandex units provided by the app owner. Shared across Android stores.
yandex.native.day=R-M-20207601-1
yandex.native.products=R-M-20207601-2
yandex.native.diary=R-M-20207601-3
yandex.native.stats=R-M-20207601-4
yandex.native.more=R-M-20207601-5
yandex.native.achievements=R-M-20207601-6
yandex.native.cloud=R-M-20207601-7
yandex.appOpenId=R-M-20207601-8
